/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1Musics200DataItemAlbumsItemPivot } from './getV1Musics200DataItemAlbumsItemPivot';

export type GetV1Musics200DataItemAlbumsItem = {
  id_album: number;
  name: string;
  /** @nullable */
  order: number | null;
  /** @nullable */
  type: string | null;
  pivot: GetV1Musics200DataItemAlbumsItemPivot;
};
