/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1MusicsId200AlbumsItem } from './getV1MusicsId200AlbumsItem';
import type { GetV1MusicsId200LyricItem } from './getV1MusicsId200LyricItem';

export type GetV1MusicsId200 = {
  id_music: number;
  name: string;
  /** @nullable */
  duration: string | null;
  /** @nullable */
  instrumental_duration: string | null;
  /** @nullable */
  url_image: string | null;
  /** @nullable */
  image_position: number | null;
  /** @nullable */
  url_music: string | null;
  /** @nullable */
  url_instrumental_music: string | null;
  lyric: GetV1MusicsId200LyricItem[];
  albums: GetV1MusicsId200AlbumsItem[];
};
