/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1Musics200DataItemAlbumsItem } from './getV1Musics200DataItemAlbumsItem';
import type { GetV1Musics200DataItemHasInstrumentalMusic } from './getV1Musics200DataItemHasInstrumentalMusic';

export type GetV1Musics200DataItem = {
  id_music: number;
  name: string;
  has_instrumental_music: typeof GetV1Musics200DataItemHasInstrumentalMusic[keyof typeof GetV1Musics200DataItemHasInstrumentalMusic];
  /** @nullable */
  duration: string | null;
  /** @nullable */
  lyric: string | null;
  /** @nullable */
  albums_names: string | null;
  albums: GetV1Musics200DataItemAlbumsItem[];
};
