/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

export type GetV1CustomCollections200DataItem = {
  id_collection: number;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  cover_url?: string | null;
  /** @nullable */
  owner_id?: number | null;
  /** @nullable */
  author_name?: string | null;
  created_at: string;
  updated_at: string;
  musics_count?: number;
};
