/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1Categories200ItemAlbumsItem } from './getV1Categories200ItemAlbumsItem';

export type GetV1Categories200Item = {
  id_category: number;
  name: string;
  slug: string;
  order: number;
  albums: GetV1Categories200ItemAlbumsItem[];
};
