/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

export type GetV1Categories200ItemAlbumsItem = {
  id_album: number;
  name: string;
  /** @nullable */
  color: string | null;
  /** @nullable */
  url_image: string | null;
  /** @nullable */
  subtitle: string | null;
  /** @nullable */
  order: number | null;
};
