/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

export type GetV1CustomMusicsIdLyrics200DataItem = {
  id_lyric: number;
  id_music: number;
  lyric: string;
  /** @nullable */
  aux_lyric: string | null;
  /** @nullable */
  id_file_image: number | null;
  time: string;
  instrumental_time: string;
  show_slide: number;
  order: number;
  created_at: string;
  updated_at: string;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  image_position?: number | null;
};
