/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

export type GetV1AlbumsParams = {
/**
 * Idioma (ex: pt, es)
 */
lang: string;
/**
 * Página atual (default: 1)
 */
page?: string;
/**
 * Itens por página (default: 50)
 */
per_page?: string;
};
