/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1CustomRanking200DataItem } from './getV1CustomRanking200DataItem';

export type GetV1CustomRanking200 = {
  data: GetV1CustomRanking200DataItem[];
};
