/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1BibleBookIdChapter200VersesItem } from './getV1BibleBookIdChapter200VersesItem';

export type GetV1BibleBookIdChapter200 = {
  id_bible_chapter: number;
  id_bible_book: number;
  chapter: number;
  verses: GetV1BibleBookIdChapter200VersesItem[];
};
