/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1AlbumsId200MusicsItemHasInstrumentalMusic } from './getV1AlbumsId200MusicsItemHasInstrumentalMusic';

export type GetV1AlbumsId200MusicsItem = {
  id_music: number;
  name: string;
  has_instrumental_music: typeof GetV1AlbumsId200MusicsItemHasInstrumentalMusic[keyof typeof GetV1AlbumsId200MusicsItemHasInstrumentalMusic];
  /** @nullable */
  duration: string | null;
  /** @nullable */
  track: number | null;
};
