/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1AlbumsId200MusicsItem } from './getV1AlbumsId200MusicsItem';

export type GetV1AlbumsId200 = {
  id_album: number;
  name: string;
  /** @nullable */
  color: string | null;
  /** @nullable */
  url_image: string | null;
  categories: string[];
  musics: GetV1AlbumsId200MusicsItem[];
};
