/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { GetV1MusicsId200LyricItemShowSlide } from './getV1MusicsId200LyricItemShowSlide';

export type GetV1MusicsId200LyricItem = {
  id_lyric: number;
  id_music: number;
  lyric: string;
  /** @nullable */
  aux_lyric: string | null;
  /** @nullable */
  url_image: string | null;
  /** @nullable */
  image_position: number | null;
  time: string;
  instrumental_time: string;
  show_slide: typeof GetV1MusicsId200LyricItemShowSlide[keyof typeof GetV1MusicsId200LyricItemShowSlide];
  order: number;
};
