/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { PostV1CustomAuthFirebaseSession200User } from './postV1CustomAuthFirebaseSession200User';

export type PostV1CustomAuthFirebaseSession200 = {
  /** @minLength 1 */
  token: string;
  user: PostV1CustomAuthFirebaseSession200User;
};
