/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { PostV1CustomFilesBodyKind } from './postV1CustomFilesBodyKind';

export type PostV1CustomFilesBody = {
  /** Arquivo (mp3, png, jpg, bmp...) */
  file: Blob | File;
  /** Subpasta de destino */
  kind?: PostV1CustomFilesBodyKind;
};
