/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

export type PostV1CustomCollectionsIdMusicsMusicIdCopy201 = {
  id_music: number;
  id_collection: number;
  name: string;
  /** @nullable */
  lyric: string | null;
  /** @nullable */
  auxiliary_lyric: string | null;
  /** @nullable */
  id_file_audio: number | null;
  /** @nullable */
  id_file_instrumental: number | null;
  /** @nullable */
  id_file_image: number | null;
  /** @nullable */
  duration: number | null;
  /** @nullable */
  official_music_id?: number | null;
  created_at: string;
  updated_at: string;
  /** @nullable */
  audio_url?: string | null;
  /** @nullable */
  instrumental_url?: string | null;
  /** @nullable */
  image_url?: string | null;
  /** @nullable */
  image_position?: number | null;
};
