/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

/**
 * Subpasta de destino
 */
export type PostV1CustomFilesBodyKind = typeof PostV1CustomFilesBodyKind[keyof typeof PostV1CustomFilesBodyKind];


export const PostV1CustomFilesBodyKind = {
  audio: 'audio',
  imagens: 'imagens',
} as const;
