/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */

export type PutV1CustomMusicsIdBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name?: string;
  lyric?: string;
  auxiliary_lyric?: string;
  id_file_audio?: number;
  id_file_instrumental?: number;
  id_file_image?: number;
  duration?: number;
};
