/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type { PutV1CustomCollectionsIdBodyVisibility } from './putV1CustomCollectionsIdBodyVisibility';

export type PutV1CustomCollectionsIdBody = {
  /**
     * @minLength 1
     * @maxLength 100
     */
  name?: string;
  /** @maxLength 500 */
  description?: string;
  /** @nullable */
  cover_url?: string | null;
  visibility?: PutV1CustomCollectionsIdBodyVisibility;
};
