/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type {
  GetV1Musics200,
  GetV1Musics500,
  GetV1MusicsId200,
  GetV1MusicsId404,
  GetV1MusicsId500,
  GetV1MusicsIdParams,
  GetV1MusicsParams
} from '../model';


export type getV1MusicsResponse200 = {
  data: GetV1Musics200
  status: 200
}

export type getV1MusicsResponse500 = {
  data: GetV1Musics500
  status: 500
}

export type getV1MusicsResponseSuccess = (getV1MusicsResponse200) & {
  headers: Headers;
};
export type getV1MusicsResponseError = (getV1MusicsResponse500) & {
  headers: Headers;
};

export type getV1MusicsResponse = (getV1MusicsResponseSuccess | getV1MusicsResponseError)

export const getGetV1MusicsUrl = (params: GetV1MusicsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/musics?${stringifiedParams}` : `/v1/musics`
}

/**
 * Lista todas as músicas com paginação e filtro por idioma (paridade: pt_musics)
 */
export const getV1Musics = async (params: GetV1MusicsParams, options?: RequestInit): Promise<getV1MusicsResponse> => {

  const res = await fetch(getGetV1MusicsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MusicsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1MusicsResponse
}


export type getV1MusicsIdResponse200 = {
  data: GetV1MusicsId200
  status: 200
}

export type getV1MusicsIdResponse404 = {
  data: GetV1MusicsId404
  status: 404
}

export type getV1MusicsIdResponse500 = {
  data: GetV1MusicsId500
  status: 500
}

export type getV1MusicsIdResponseSuccess = (getV1MusicsIdResponse200) & {
  headers: Headers;
};
export type getV1MusicsIdResponseError = (getV1MusicsIdResponse404 | getV1MusicsIdResponse500) & {
  headers: Headers;
};

export type getV1MusicsIdResponse = (getV1MusicsIdResponseSuccess | getV1MusicsIdResponseError)

export const getGetV1MusicsIdUrl = (id: string,
    params: GetV1MusicsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/musics/${id}?${stringifiedParams}` : `/v1/musics/${id}`
}

/**
 * Detalhe de uma música com letras (estrofes) e URLs de mídia (paridade: music_{id})
 */
export const getV1MusicsId = async (id: string,
    params: GetV1MusicsIdParams, options?: RequestInit): Promise<getV1MusicsIdResponse> => {

  const res = await fetch(getGetV1MusicsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MusicsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1MusicsIdResponse
}


