/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type {
  GetV1Bible200,
  GetV1Bible500,
  GetV1BibleBookIdChapter200,
  GetV1BibleBookIdChapter404,
  GetV1BibleBookIdChapter500,
  GetV1BibleBookIdChapterParams,
  GetV1BibleParams
} from '../model';


export type getV1BibleResponse200 = {
  data: GetV1Bible200
  status: 200
}

export type getV1BibleResponse500 = {
  data: GetV1Bible500
  status: 500
}

export type getV1BibleResponseSuccess = (getV1BibleResponse200) & {
  headers: Headers;
};
export type getV1BibleResponseError = (getV1BibleResponse500) & {
  headers: Headers;
};

export type getV1BibleResponse = (getV1BibleResponseSuccess | getV1BibleResponseError)

export const getGetV1BibleUrl = (params?: GetV1BibleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/bible?${stringifiedParams}` : `/v1/bible`
}

/**
 * Lista completa dos livros da Biblia de acordo com o idioma.
 * @summary Lista de livros da Biblia
 */
export const getV1Bible = async (params?: GetV1BibleParams, options?: RequestInit): Promise<getV1BibleResponse> => {

  const res = await fetch(getGetV1BibleUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1BibleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1BibleResponse
}


export type getV1BibleBookIdChapterResponse200 = {
  data: GetV1BibleBookIdChapter200
  status: 200
}

export type getV1BibleBookIdChapterResponse404 = {
  data: GetV1BibleBookIdChapter404
  status: 404
}

export type getV1BibleBookIdChapterResponse500 = {
  data: GetV1BibleBookIdChapter500
  status: 500
}

export type getV1BibleBookIdChapterResponseSuccess = (getV1BibleBookIdChapterResponse200) & {
  headers: Headers;
};
export type getV1BibleBookIdChapterResponseError = (getV1BibleBookIdChapterResponse404 | getV1BibleBookIdChapterResponse500) & {
  headers: Headers;
};

export type getV1BibleBookIdChapterResponse = (getV1BibleBookIdChapterResponseSuccess | getV1BibleBookIdChapterResponseError)

export const getGetV1BibleBookIdChapterUrl = (bookId: string,
    chapter: string,
    params?: GetV1BibleBookIdChapterParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/bible/${bookId}/${chapter}?${stringifiedParams}` : `/v1/bible/${bookId}/${chapter}`
}

/**
 * Retorna todos os versiculos de um capitulo especifico de um livro.
 * @summary Obtem um capitulo da Biblia
 */
export const getV1BibleBookIdChapter = async (bookId: string,
    chapter: string,
    params?: GetV1BibleBookIdChapterParams, options?: RequestInit): Promise<getV1BibleBookIdChapterResponse> => {

  const res = await fetch(getGetV1BibleBookIdChapterUrl(bookId,chapter,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1BibleBookIdChapterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1BibleBookIdChapterResponse
}


