/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type {
  DeleteV1CustomCollectionsId200,
  DeleteV1CustomCollectionsId401,
  DeleteV1CustomCollectionsId403,
  DeleteV1CustomCollectionsId404,
  DeleteV1CustomCollectionsId500,
  DeleteV1CustomLyricsId200,
  DeleteV1CustomLyricsId404,
  DeleteV1CustomLyricsId500,
  DeleteV1CustomMusicsId200,
  DeleteV1CustomMusicsId401,
  DeleteV1CustomMusicsId403,
  DeleteV1CustomMusicsId404,
  DeleteV1CustomMusicsId500,
  GetV1CustomAuthMe200,
  GetV1CustomAuthMe401,
  GetV1CustomCollections200,
  GetV1CustomCollections500,
  GetV1CustomCollectionsId200,
  GetV1CustomCollectionsId404,
  GetV1CustomCollectionsId500,
  GetV1CustomCollectionsIdMusics200,
  GetV1CustomCollectionsIdMusics500,
  GetV1CustomMusics200,
  GetV1CustomMusics500,
  GetV1CustomMusicsId200,
  GetV1CustomMusicsId404,
  GetV1CustomMusicsId500,
  GetV1CustomMusicsIdLyrics200,
  GetV1CustomMusicsIdLyrics500,
  GetV1CustomNotifications200,
  GetV1CustomNotifications401,
  GetV1CustomRanking200,
  GetV1CustomRankingMe200,
  GetV1CustomRankingMe401,
  GetV1CustomRankingMeParams,
  GetV1CustomRankingParams,
  GetV1CustomSeasonalEvent200,
  GetV1CustomWeeklyTasks200,
  GetV1CustomWeeklyTasks401,
  PostV1CustomAdminPromoteMusic200,
  PostV1CustomAdminPromoteMusic400,
  PostV1CustomAdminPromoteMusic401,
  PostV1CustomAdminPromoteMusic403,
  PostV1CustomAdminPromoteMusicBody,
  PostV1CustomAuthFirebaseSession200,
  PostV1CustomAuthFirebaseSession401,
  PostV1CustomAuthForgotPassword200,
  PostV1CustomAuthForgotPassword500,
  PostV1CustomAuthForgotPasswordBody,
  PostV1CustomAuthLogin200,
  PostV1CustomAuthLogin401,
  PostV1CustomAuthLogin500,
  PostV1CustomAuthLoginBody,
  PostV1CustomAuthLogout401,
  PostV1CustomAuthRegister201,
  PostV1CustomAuthRegister409,
  PostV1CustomAuthRegister422,
  PostV1CustomAuthRegister500,
  PostV1CustomAuthRegisterBody,
  PostV1CustomAuthResetPassword200,
  PostV1CustomAuthResetPassword400,
  PostV1CustomAuthResetPassword500,
  PostV1CustomAuthResetPasswordBody,
  PostV1CustomCollections201,
  PostV1CustomCollections400,
  PostV1CustomCollections401,
  PostV1CustomCollections500,
  PostV1CustomCollectionsBody,
  PostV1CustomCollectionsIdMusics201,
  PostV1CustomCollectionsIdMusics404,
  PostV1CustomCollectionsIdMusics500,
  PostV1CustomCollectionsIdMusicsBody,
  PostV1CustomCollectionsIdMusicsMusicIdCopy200,
  PostV1CustomCollectionsIdMusicsMusicIdCopy201,
  PostV1CustomCollectionsIdMusicsMusicIdCopy404,
  PostV1CustomCollectionsIdMusicsMusicIdCopy500,
  PostV1CustomCollectionsIdReport200,
  PostV1CustomCollectionsIdReport401,
  PostV1CustomCollectionsIdReport404,
  PostV1CustomCollectionsIdReportBody,
  PostV1CustomCollectionsIdUse200,
  PostV1CustomCollectionsIdUse401,
  PostV1CustomCollectionsIdUse404,
  PostV1CustomFiles201,
  PostV1CustomFiles400,
  PostV1CustomFiles500,
  PostV1CustomFilesBody,
  PostV1CustomMusicsIdLyrics201,
  PostV1CustomMusicsIdLyrics404,
  PostV1CustomMusicsIdLyrics500,
  PostV1CustomMusicsIdLyricsBody,
  PostV1CustomNotificationsReadAll200,
  PostV1CustomNotificationsReadAll401,
  PostV1CustomWeeklyTasksTaskIdComplete200,
  PostV1CustomWeeklyTasksTaskIdComplete401,
  PostV1CustomWeeklyTasksTaskIdComplete404,
  PutV1CustomCollectionsId200,
  PutV1CustomCollectionsId401,
  PutV1CustomCollectionsId403,
  PutV1CustomCollectionsId404,
  PutV1CustomCollectionsId500,
  PutV1CustomCollectionsIdBody,
  PutV1CustomLyricsId200,
  PutV1CustomLyricsId404,
  PutV1CustomLyricsId500,
  PutV1CustomLyricsIdBody,
  PutV1CustomMusicsId200,
  PutV1CustomMusicsId401,
  PutV1CustomMusicsId403,
  PutV1CustomMusicsId404,
  PutV1CustomMusicsId500,
  PutV1CustomMusicsIdBody
} from '../model';


export type getV1CustomCollectionsResponse200 = {
  data: GetV1CustomCollections200
  status: 200
}

export type getV1CustomCollectionsResponse500 = {
  data: GetV1CustomCollections500
  status: 500
}

export type getV1CustomCollectionsResponseSuccess = (getV1CustomCollectionsResponse200) & {
  headers: Headers;
};
export type getV1CustomCollectionsResponseError = (getV1CustomCollectionsResponse500) & {
  headers: Headers;
};

export type getV1CustomCollectionsResponse = (getV1CustomCollectionsResponseSuccess | getV1CustomCollectionsResponseError)

export const getGetV1CustomCollectionsUrl = () => {




  return `/v1/custom/collections`
}

/**
 * Lista coletâneas customizadas (públicas + minhas se autenticado)
 */
export const getV1CustomCollections = async ( options?: RequestInit): Promise<getV1CustomCollectionsResponse> => {

  const res = await fetch(getGetV1CustomCollectionsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomCollectionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomCollectionsResponse
}


export type postV1CustomCollectionsResponse201 = {
  data: PostV1CustomCollections201
  status: 201
}

export type postV1CustomCollectionsResponse400 = {
  data: PostV1CustomCollections400
  status: 400
}

export type postV1CustomCollectionsResponse401 = {
  data: PostV1CustomCollections401
  status: 401
}

export type postV1CustomCollectionsResponse500 = {
  data: PostV1CustomCollections500
  status: 500
}

export type postV1CustomCollectionsResponseSuccess = (postV1CustomCollectionsResponse201) & {
  headers: Headers;
};
export type postV1CustomCollectionsResponseError = (postV1CustomCollectionsResponse400 | postV1CustomCollectionsResponse401 | postV1CustomCollectionsResponse500) & {
  headers: Headers;
};

export type postV1CustomCollectionsResponse = (postV1CustomCollectionsResponseSuccess | postV1CustomCollectionsResponseError)

export const getPostV1CustomCollectionsUrl = () => {




  return `/v1/custom/collections`
}

/**
 * Cria uma nova coletânea customizada
 */
export const postV1CustomCollections = async (postV1CustomCollectionsBody?: PostV1CustomCollectionsBody, options?: RequestInit): Promise<postV1CustomCollectionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomCollectionsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomCollectionsBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomCollectionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomCollectionsResponse
}


export type getV1CustomCollectionsIdResponse200 = {
  data: GetV1CustomCollectionsId200
  status: 200
}

export type getV1CustomCollectionsIdResponse404 = {
  data: GetV1CustomCollectionsId404
  status: 404
}

export type getV1CustomCollectionsIdResponse500 = {
  data: GetV1CustomCollectionsId500
  status: 500
}

export type getV1CustomCollectionsIdResponseSuccess = (getV1CustomCollectionsIdResponse200) & {
  headers: Headers;
};
export type getV1CustomCollectionsIdResponseError = (getV1CustomCollectionsIdResponse404 | getV1CustomCollectionsIdResponse500) & {
  headers: Headers;
};

export type getV1CustomCollectionsIdResponse = (getV1CustomCollectionsIdResponseSuccess | getV1CustomCollectionsIdResponseError)

export const getGetV1CustomCollectionsIdUrl = (id: string,) => {




  return `/v1/custom/collections/${id}`
}

/**
 * Detalhe de uma coletânea customizada
 */
export const getV1CustomCollectionsId = async (id: string, options?: RequestInit): Promise<getV1CustomCollectionsIdResponse> => {

  const res = await fetch(getGetV1CustomCollectionsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomCollectionsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomCollectionsIdResponse
}


export type putV1CustomCollectionsIdResponse200 = {
  data: PutV1CustomCollectionsId200
  status: 200
}

export type putV1CustomCollectionsIdResponse401 = {
  data: PutV1CustomCollectionsId401
  status: 401
}

export type putV1CustomCollectionsIdResponse403 = {
  data: PutV1CustomCollectionsId403
  status: 403
}

export type putV1CustomCollectionsIdResponse404 = {
  data: PutV1CustomCollectionsId404
  status: 404
}

export type putV1CustomCollectionsIdResponse500 = {
  data: PutV1CustomCollectionsId500
  status: 500
}

export type putV1CustomCollectionsIdResponseSuccess = (putV1CustomCollectionsIdResponse200) & {
  headers: Headers;
};
export type putV1CustomCollectionsIdResponseError = (putV1CustomCollectionsIdResponse401 | putV1CustomCollectionsIdResponse403 | putV1CustomCollectionsIdResponse404 | putV1CustomCollectionsIdResponse500) & {
  headers: Headers;
};

export type putV1CustomCollectionsIdResponse = (putV1CustomCollectionsIdResponseSuccess | putV1CustomCollectionsIdResponseError)

export const getPutV1CustomCollectionsIdUrl = (id: string,) => {




  return `/v1/custom/collections/${id}`
}

/**
 * Atualiza uma coletânea customizada
 */
export const putV1CustomCollectionsId = async (id: string,
    putV1CustomCollectionsIdBody?: PutV1CustomCollectionsIdBody, options?: RequestInit): Promise<putV1CustomCollectionsIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutV1CustomCollectionsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(putV1CustomCollectionsIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putV1CustomCollectionsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putV1CustomCollectionsIdResponse
}


export type deleteV1CustomCollectionsIdResponse200 = {
  data: DeleteV1CustomCollectionsId200
  status: 200
}

export type deleteV1CustomCollectionsIdResponse401 = {
  data: DeleteV1CustomCollectionsId401
  status: 401
}

export type deleteV1CustomCollectionsIdResponse403 = {
  data: DeleteV1CustomCollectionsId403
  status: 403
}

export type deleteV1CustomCollectionsIdResponse404 = {
  data: DeleteV1CustomCollectionsId404
  status: 404
}

export type deleteV1CustomCollectionsIdResponse500 = {
  data: DeleteV1CustomCollectionsId500
  status: 500
}

export type deleteV1CustomCollectionsIdResponseSuccess = (deleteV1CustomCollectionsIdResponse200) & {
  headers: Headers;
};
export type deleteV1CustomCollectionsIdResponseError = (deleteV1CustomCollectionsIdResponse401 | deleteV1CustomCollectionsIdResponse403 | deleteV1CustomCollectionsIdResponse404 | deleteV1CustomCollectionsIdResponse500) & {
  headers: Headers;
};

export type deleteV1CustomCollectionsIdResponse = (deleteV1CustomCollectionsIdResponseSuccess | deleteV1CustomCollectionsIdResponseError)

export const getDeleteV1CustomCollectionsIdUrl = (id: string,) => {




  return `/v1/custom/collections/${id}`
}

/**
 * Remove uma coletânea customizada (cascade em músicas)
 */
export const deleteV1CustomCollectionsId = async (id: string, options?: RequestInit): Promise<deleteV1CustomCollectionsIdResponse> => {

  const res = await fetch(getDeleteV1CustomCollectionsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1CustomCollectionsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteV1CustomCollectionsIdResponse
}


export type getV1CustomMusicsResponse200 = {
  data: GetV1CustomMusics200
  status: 200
}

export type getV1CustomMusicsResponse500 = {
  data: GetV1CustomMusics500
  status: 500
}

export type getV1CustomMusicsResponseSuccess = (getV1CustomMusicsResponse200) & {
  headers: Headers;
};
export type getV1CustomMusicsResponseError = (getV1CustomMusicsResponse500) & {
  headers: Headers;
};

export type getV1CustomMusicsResponse = (getV1CustomMusicsResponseSuccess | getV1CustomMusicsResponseError)

export const getGetV1CustomMusicsUrl = () => {




  return `/v1/custom/musics`
}

/**
 * Lista todas as músicas custom (de todas as coletâneas)
 */
export const getV1CustomMusics = async ( options?: RequestInit): Promise<getV1CustomMusicsResponse> => {

  const res = await fetch(getGetV1CustomMusicsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomMusicsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomMusicsResponse
}


export type getV1CustomCollectionsIdMusicsResponse200 = {
  data: GetV1CustomCollectionsIdMusics200
  status: 200
}

export type getV1CustomCollectionsIdMusicsResponse500 = {
  data: GetV1CustomCollectionsIdMusics500
  status: 500
}

export type getV1CustomCollectionsIdMusicsResponseSuccess = (getV1CustomCollectionsIdMusicsResponse200) & {
  headers: Headers;
};
export type getV1CustomCollectionsIdMusicsResponseError = (getV1CustomCollectionsIdMusicsResponse500) & {
  headers: Headers;
};

export type getV1CustomCollectionsIdMusicsResponse = (getV1CustomCollectionsIdMusicsResponseSuccess | getV1CustomCollectionsIdMusicsResponseError)

export const getGetV1CustomCollectionsIdMusicsUrl = (id: string,) => {




  return `/v1/custom/collections/${id}/musics`
}

/**
 * Lista músicas de uma coletânea customizada
 */
export const getV1CustomCollectionsIdMusics = async (id: string, options?: RequestInit): Promise<getV1CustomCollectionsIdMusicsResponse> => {

  const res = await fetch(getGetV1CustomCollectionsIdMusicsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomCollectionsIdMusicsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomCollectionsIdMusicsResponse
}


export type postV1CustomCollectionsIdMusicsResponse201 = {
  data: PostV1CustomCollectionsIdMusics201
  status: 201
}

export type postV1CustomCollectionsIdMusicsResponse404 = {
  data: PostV1CustomCollectionsIdMusics404
  status: 404
}

export type postV1CustomCollectionsIdMusicsResponse500 = {
  data: PostV1CustomCollectionsIdMusics500
  status: 500
}

export type postV1CustomCollectionsIdMusicsResponseSuccess = (postV1CustomCollectionsIdMusicsResponse201) & {
  headers: Headers;
};
export type postV1CustomCollectionsIdMusicsResponseError = (postV1CustomCollectionsIdMusicsResponse404 | postV1CustomCollectionsIdMusicsResponse500) & {
  headers: Headers;
};

export type postV1CustomCollectionsIdMusicsResponse = (postV1CustomCollectionsIdMusicsResponseSuccess | postV1CustomCollectionsIdMusicsResponseError)

export const getPostV1CustomCollectionsIdMusicsUrl = (id: string,) => {




  return `/v1/custom/collections/${id}/musics`
}

/**
 * Cria uma nova música em uma coletânea customizada
 */
export const postV1CustomCollectionsIdMusics = async (id: string,
    postV1CustomCollectionsIdMusicsBody?: PostV1CustomCollectionsIdMusicsBody, options?: RequestInit): Promise<postV1CustomCollectionsIdMusicsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomCollectionsIdMusicsUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomCollectionsIdMusicsBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomCollectionsIdMusicsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomCollectionsIdMusicsResponse
}


export type postV1CustomCollectionsIdMusicsMusicIdCopyResponse200 = {
  data: PostV1CustomCollectionsIdMusicsMusicIdCopy200
  status: 200
}

export type postV1CustomCollectionsIdMusicsMusicIdCopyResponse201 = {
  data: PostV1CustomCollectionsIdMusicsMusicIdCopy201
  status: 201
}

export type postV1CustomCollectionsIdMusicsMusicIdCopyResponse404 = {
  data: PostV1CustomCollectionsIdMusicsMusicIdCopy404
  status: 404
}

export type postV1CustomCollectionsIdMusicsMusicIdCopyResponse500 = {
  data: PostV1CustomCollectionsIdMusicsMusicIdCopy500
  status: 500
}

export type postV1CustomCollectionsIdMusicsMusicIdCopyResponseSuccess = (postV1CustomCollectionsIdMusicsMusicIdCopyResponse200 | postV1CustomCollectionsIdMusicsMusicIdCopyResponse201) & {
  headers: Headers;
};
export type postV1CustomCollectionsIdMusicsMusicIdCopyResponseError = (postV1CustomCollectionsIdMusicsMusicIdCopyResponse404 | postV1CustomCollectionsIdMusicsMusicIdCopyResponse500) & {
  headers: Headers;
};

export type postV1CustomCollectionsIdMusicsMusicIdCopyResponse = (postV1CustomCollectionsIdMusicsMusicIdCopyResponseSuccess | postV1CustomCollectionsIdMusicsMusicIdCopyResponseError)

export const getPostV1CustomCollectionsIdMusicsMusicIdCopyUrl = (id: string,
    musicId: string,) => {




  return `/v1/custom/collections/${id}/musics/${musicId}/copy`
}

/**
 * Copia uma música custom existente para esta coletânea (com letra e mídia)
 */
export const postV1CustomCollectionsIdMusicsMusicIdCopy = async (id: string,
    musicId: string, options?: RequestInit): Promise<postV1CustomCollectionsIdMusicsMusicIdCopyResponse> => {

  const res = await fetch(getPostV1CustomCollectionsIdMusicsMusicIdCopyUrl(id,musicId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomCollectionsIdMusicsMusicIdCopyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomCollectionsIdMusicsMusicIdCopyResponse
}


export type getV1CustomMusicsIdResponse200 = {
  data: GetV1CustomMusicsId200
  status: 200
}

export type getV1CustomMusicsIdResponse404 = {
  data: GetV1CustomMusicsId404
  status: 404
}

export type getV1CustomMusicsIdResponse500 = {
  data: GetV1CustomMusicsId500
  status: 500
}

export type getV1CustomMusicsIdResponseSuccess = (getV1CustomMusicsIdResponse200) & {
  headers: Headers;
};
export type getV1CustomMusicsIdResponseError = (getV1CustomMusicsIdResponse404 | getV1CustomMusicsIdResponse500) & {
  headers: Headers;
};

export type getV1CustomMusicsIdResponse = (getV1CustomMusicsIdResponseSuccess | getV1CustomMusicsIdResponseError)

export const getGetV1CustomMusicsIdUrl = (id: string,) => {




  return `/v1/custom/musics/${id}`
}

/**
 * Detalhe de uma música customizada com estrofes
 */
export const getV1CustomMusicsId = async (id: string, options?: RequestInit): Promise<getV1CustomMusicsIdResponse> => {

  const res = await fetch(getGetV1CustomMusicsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomMusicsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomMusicsIdResponse
}


export type putV1CustomMusicsIdResponse200 = {
  data: PutV1CustomMusicsId200
  status: 200
}

export type putV1CustomMusicsIdResponse401 = {
  data: PutV1CustomMusicsId401
  status: 401
}

export type putV1CustomMusicsIdResponse403 = {
  data: PutV1CustomMusicsId403
  status: 403
}

export type putV1CustomMusicsIdResponse404 = {
  data: PutV1CustomMusicsId404
  status: 404
}

export type putV1CustomMusicsIdResponse500 = {
  data: PutV1CustomMusicsId500
  status: 500
}

export type putV1CustomMusicsIdResponseSuccess = (putV1CustomMusicsIdResponse200) & {
  headers: Headers;
};
export type putV1CustomMusicsIdResponseError = (putV1CustomMusicsIdResponse401 | putV1CustomMusicsIdResponse403 | putV1CustomMusicsIdResponse404 | putV1CustomMusicsIdResponse500) & {
  headers: Headers;
};

export type putV1CustomMusicsIdResponse = (putV1CustomMusicsIdResponseSuccess | putV1CustomMusicsIdResponseError)

export const getPutV1CustomMusicsIdUrl = (id: string,) => {




  return `/v1/custom/musics/${id}`
}

/**
 * Atualiza uma música customizada
 */
export const putV1CustomMusicsId = async (id: string,
    putV1CustomMusicsIdBody?: PutV1CustomMusicsIdBody, options?: RequestInit): Promise<putV1CustomMusicsIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutV1CustomMusicsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(putV1CustomMusicsIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putV1CustomMusicsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putV1CustomMusicsIdResponse
}


export type deleteV1CustomMusicsIdResponse200 = {
  data: DeleteV1CustomMusicsId200
  status: 200
}

export type deleteV1CustomMusicsIdResponse401 = {
  data: DeleteV1CustomMusicsId401
  status: 401
}

export type deleteV1CustomMusicsIdResponse403 = {
  data: DeleteV1CustomMusicsId403
  status: 403
}

export type deleteV1CustomMusicsIdResponse404 = {
  data: DeleteV1CustomMusicsId404
  status: 404
}

export type deleteV1CustomMusicsIdResponse500 = {
  data: DeleteV1CustomMusicsId500
  status: 500
}

export type deleteV1CustomMusicsIdResponseSuccess = (deleteV1CustomMusicsIdResponse200) & {
  headers: Headers;
};
export type deleteV1CustomMusicsIdResponseError = (deleteV1CustomMusicsIdResponse401 | deleteV1CustomMusicsIdResponse403 | deleteV1CustomMusicsIdResponse404 | deleteV1CustomMusicsIdResponse500) & {
  headers: Headers;
};

export type deleteV1CustomMusicsIdResponse = (deleteV1CustomMusicsIdResponseSuccess | deleteV1CustomMusicsIdResponseError)

export const getDeleteV1CustomMusicsIdUrl = (id: string,) => {




  return `/v1/custom/musics/${id}`
}

/**
 * Remove uma música customizada (cascade em estrofes)
 */
export const deleteV1CustomMusicsId = async (id: string, options?: RequestInit): Promise<deleteV1CustomMusicsIdResponse> => {

  const res = await fetch(getDeleteV1CustomMusicsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1CustomMusicsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteV1CustomMusicsIdResponse
}


export type getV1CustomMusicsIdLyricsResponse200 = {
  data: GetV1CustomMusicsIdLyrics200
  status: 200
}

export type getV1CustomMusicsIdLyricsResponse500 = {
  data: GetV1CustomMusicsIdLyrics500
  status: 500
}

export type getV1CustomMusicsIdLyricsResponseSuccess = (getV1CustomMusicsIdLyricsResponse200) & {
  headers: Headers;
};
export type getV1CustomMusicsIdLyricsResponseError = (getV1CustomMusicsIdLyricsResponse500) & {
  headers: Headers;
};

export type getV1CustomMusicsIdLyricsResponse = (getV1CustomMusicsIdLyricsResponseSuccess | getV1CustomMusicsIdLyricsResponseError)

export const getGetV1CustomMusicsIdLyricsUrl = (id: string,) => {




  return `/v1/custom/musics/${id}/lyrics`
}

/**
 * Lista estrofes de uma música customizada
 */
export const getV1CustomMusicsIdLyrics = async (id: string, options?: RequestInit): Promise<getV1CustomMusicsIdLyricsResponse> => {

  const res = await fetch(getGetV1CustomMusicsIdLyricsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomMusicsIdLyricsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomMusicsIdLyricsResponse
}


export type postV1CustomMusicsIdLyricsResponse201 = {
  data: PostV1CustomMusicsIdLyrics201
  status: 201
}

export type postV1CustomMusicsIdLyricsResponse404 = {
  data: PostV1CustomMusicsIdLyrics404
  status: 404
}

export type postV1CustomMusicsIdLyricsResponse500 = {
  data: PostV1CustomMusicsIdLyrics500
  status: 500
}

export type postV1CustomMusicsIdLyricsResponseSuccess = (postV1CustomMusicsIdLyricsResponse201) & {
  headers: Headers;
};
export type postV1CustomMusicsIdLyricsResponseError = (postV1CustomMusicsIdLyricsResponse404 | postV1CustomMusicsIdLyricsResponse500) & {
  headers: Headers;
};

export type postV1CustomMusicsIdLyricsResponse = (postV1CustomMusicsIdLyricsResponseSuccess | postV1CustomMusicsIdLyricsResponseError)

export const getPostV1CustomMusicsIdLyricsUrl = (id: string,) => {




  return `/v1/custom/musics/${id}/lyrics`
}

/**
 * Cria uma nova estrofe em uma música customizada
 */
export const postV1CustomMusicsIdLyrics = async (id: string,
    postV1CustomMusicsIdLyricsBody?: PostV1CustomMusicsIdLyricsBody, options?: RequestInit): Promise<postV1CustomMusicsIdLyricsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomMusicsIdLyricsUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomMusicsIdLyricsBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomMusicsIdLyricsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomMusicsIdLyricsResponse
}


export type putV1CustomLyricsIdResponse200 = {
  data: PutV1CustomLyricsId200
  status: 200
}

export type putV1CustomLyricsIdResponse404 = {
  data: PutV1CustomLyricsId404
  status: 404
}

export type putV1CustomLyricsIdResponse500 = {
  data: PutV1CustomLyricsId500
  status: 500
}

export type putV1CustomLyricsIdResponseSuccess = (putV1CustomLyricsIdResponse200) & {
  headers: Headers;
};
export type putV1CustomLyricsIdResponseError = (putV1CustomLyricsIdResponse404 | putV1CustomLyricsIdResponse500) & {
  headers: Headers;
};

export type putV1CustomLyricsIdResponse = (putV1CustomLyricsIdResponseSuccess | putV1CustomLyricsIdResponseError)

export const getPutV1CustomLyricsIdUrl = (id: string,) => {




  return `/v1/custom/lyrics/${id}`
}

/**
 * Atualiza uma estrofe
 */
export const putV1CustomLyricsId = async (id: string,
    putV1CustomLyricsIdBody?: PutV1CustomLyricsIdBody, options?: RequestInit): Promise<putV1CustomLyricsIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutV1CustomLyricsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(putV1CustomLyricsIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putV1CustomLyricsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putV1CustomLyricsIdResponse
}


export type deleteV1CustomLyricsIdResponse200 = {
  data: DeleteV1CustomLyricsId200
  status: 200
}

export type deleteV1CustomLyricsIdResponse404 = {
  data: DeleteV1CustomLyricsId404
  status: 404
}

export type deleteV1CustomLyricsIdResponse500 = {
  data: DeleteV1CustomLyricsId500
  status: 500
}

export type deleteV1CustomLyricsIdResponseSuccess = (deleteV1CustomLyricsIdResponse200) & {
  headers: Headers;
};
export type deleteV1CustomLyricsIdResponseError = (deleteV1CustomLyricsIdResponse404 | deleteV1CustomLyricsIdResponse500) & {
  headers: Headers;
};

export type deleteV1CustomLyricsIdResponse = (deleteV1CustomLyricsIdResponseSuccess | deleteV1CustomLyricsIdResponseError)

export const getDeleteV1CustomLyricsIdUrl = (id: string,) => {




  return `/v1/custom/lyrics/${id}`
}

/**
 * Remove uma estrofe
 */
export const deleteV1CustomLyricsId = async (id: string, options?: RequestInit): Promise<deleteV1CustomLyricsIdResponse> => {

  const res = await fetch(getDeleteV1CustomLyricsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1CustomLyricsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteV1CustomLyricsIdResponse
}


export type postV1CustomFilesResponse201 = {
  data: PostV1CustomFiles201
  status: 201
}

export type postV1CustomFilesResponse400 = {
  data: PostV1CustomFiles400
  status: 400
}

export type postV1CustomFilesResponse500 = {
  data: PostV1CustomFiles500
  status: 500
}

export type postV1CustomFilesResponseSuccess = (postV1CustomFilesResponse201) & {
  headers: Headers;
};
export type postV1CustomFilesResponseError = (postV1CustomFilesResponse400 | postV1CustomFilesResponse500) & {
  headers: Headers;
};

export type postV1CustomFilesResponse = (postV1CustomFilesResponseSuccess | postV1CustomFilesResponseError)

export const getPostV1CustomFilesUrl = () => {




  return `/v1/custom/files`
}

/**
 * Upload de arquivo de mídia custom (áudio ou imagem) para uso em músicas/coletâneas
 */
export const postV1CustomFiles = async (postV1CustomFilesBody?: PostV1CustomFilesBody, options?: RequestInit): Promise<postV1CustomFilesResponse> => {
    const formData = new FormData();
if(postV1CustomFilesBody?.file !== undefined) {
 formData.append(`file`, postV1CustomFilesBody.file);
 }
if(postV1CustomFilesBody?.kind !== undefined) {
 formData.append(`kind`, postV1CustomFilesBody.kind);
 }

  const res = await fetch(getPostV1CustomFilesUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomFilesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomFilesResponse
}


export type postV1CustomAuthRegisterResponse201 = {
  data: PostV1CustomAuthRegister201
  status: 201
}

export type postV1CustomAuthRegisterResponse409 = {
  data: PostV1CustomAuthRegister409
  status: 409
}

export type postV1CustomAuthRegisterResponse422 = {
  data: PostV1CustomAuthRegister422
  status: 422
}

export type postV1CustomAuthRegisterResponse500 = {
  data: PostV1CustomAuthRegister500
  status: 500
}

export type postV1CustomAuthRegisterResponseSuccess = (postV1CustomAuthRegisterResponse201) & {
  headers: Headers;
};
export type postV1CustomAuthRegisterResponseError = (postV1CustomAuthRegisterResponse409 | postV1CustomAuthRegisterResponse422 | postV1CustomAuthRegisterResponse500) & {
  headers: Headers;
};

export type postV1CustomAuthRegisterResponse = (postV1CustomAuthRegisterResponseSuccess | postV1CustomAuthRegisterResponseError)

export const getPostV1CustomAuthRegisterUrl = () => {




  return `/v1/custom/auth/register`
}

/**
 * Registra um novo usuário de coletâneas custom
 */
export const postV1CustomAuthRegister = async (postV1CustomAuthRegisterBody?: PostV1CustomAuthRegisterBody, options?: RequestInit): Promise<postV1CustomAuthRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomAuthRegisterBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAuthRegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomAuthRegisterResponse
}


export type postV1CustomAuthLoginResponse200 = {
  data: PostV1CustomAuthLogin200
  status: 200
}

export type postV1CustomAuthLoginResponse401 = {
  data: PostV1CustomAuthLogin401
  status: 401
}

export type postV1CustomAuthLoginResponse500 = {
  data: PostV1CustomAuthLogin500
  status: 500
}

export type postV1CustomAuthLoginResponseSuccess = (postV1CustomAuthLoginResponse200) & {
  headers: Headers;
};
export type postV1CustomAuthLoginResponseError = (postV1CustomAuthLoginResponse401 | postV1CustomAuthLoginResponse500) & {
  headers: Headers;
};

export type postV1CustomAuthLoginResponse = (postV1CustomAuthLoginResponseSuccess | postV1CustomAuthLoginResponseError)

export const getPostV1CustomAuthLoginUrl = () => {




  return `/v1/custom/auth/login`
}

/**
 * Login de usuário de coletâneas custom
 */
export const postV1CustomAuthLogin = async (postV1CustomAuthLoginBody?: PostV1CustomAuthLoginBody, options?: RequestInit): Promise<postV1CustomAuthLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomAuthLoginBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAuthLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomAuthLoginResponse
}


export type postV1CustomAuthFirebaseSessionResponse200 = {
  data: PostV1CustomAuthFirebaseSession200
  status: 200
}

export type postV1CustomAuthFirebaseSessionResponse401 = {
  data: PostV1CustomAuthFirebaseSession401
  status: 401
}

export type postV1CustomAuthFirebaseSessionResponseSuccess = (postV1CustomAuthFirebaseSessionResponse200) & {
  headers: Headers;
};
export type postV1CustomAuthFirebaseSessionResponseError = (postV1CustomAuthFirebaseSessionResponse401) & {
  headers: Headers;
};

export type postV1CustomAuthFirebaseSessionResponse = (postV1CustomAuthFirebaseSessionResponseSuccess | postV1CustomAuthFirebaseSessionResponseError)

export const getPostV1CustomAuthFirebaseSessionUrl = () => {




  return `/v1/custom/auth/firebase-session`
}

/**
 * Valida Firebase ID token (Bearer) e devolve sessão com id_user real
 */
export const postV1CustomAuthFirebaseSession = async ( options?: RequestInit): Promise<postV1CustomAuthFirebaseSessionResponse> => {

  const res = await fetch(getPostV1CustomAuthFirebaseSessionUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAuthFirebaseSessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomAuthFirebaseSessionResponse
}


export type postV1CustomAuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postV1CustomAuthLogoutResponse401 = {
  data: PostV1CustomAuthLogout401
  status: 401
}

export type postV1CustomAuthLogoutResponseSuccess = (postV1CustomAuthLogoutResponse204) & {
  headers: Headers;
};
export type postV1CustomAuthLogoutResponseError = (postV1CustomAuthLogoutResponse401) & {
  headers: Headers;
};

export type postV1CustomAuthLogoutResponse = (postV1CustomAuthLogoutResponseSuccess | postV1CustomAuthLogoutResponseError)

export const getPostV1CustomAuthLogoutUrl = () => {




  return `/v1/custom/auth/logout`
}

/**
 * Logout — invalida token da sessão
 */
export const postV1CustomAuthLogout = async ( options?: RequestInit): Promise<postV1CustomAuthLogoutResponse> => {

  const res = await fetch(getPostV1CustomAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAuthLogoutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postV1CustomAuthLogoutResponse
}


export type getV1CustomAuthMeResponse200 = {
  data: GetV1CustomAuthMe200
  status: 200
}

export type getV1CustomAuthMeResponse401 = {
  data: GetV1CustomAuthMe401
  status: 401
}

export type getV1CustomAuthMeResponseSuccess = (getV1CustomAuthMeResponse200) & {
  headers: Headers;
};
export type getV1CustomAuthMeResponseError = (getV1CustomAuthMeResponse401) & {
  headers: Headers;
};

export type getV1CustomAuthMeResponse = (getV1CustomAuthMeResponseSuccess | getV1CustomAuthMeResponseError)

export const getGetV1CustomAuthMeUrl = () => {




  return `/v1/custom/auth/me`
}

/**
 * Usuário autenticado atual
 */
export const getV1CustomAuthMe = async ( options?: RequestInit): Promise<getV1CustomAuthMeResponse> => {

  const res = await fetch(getGetV1CustomAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomAuthMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomAuthMeResponse
}


export type postV1CustomAuthForgotPasswordResponse200 = {
  data: PostV1CustomAuthForgotPassword200
  status: 200
}

export type postV1CustomAuthForgotPasswordResponse500 = {
  data: PostV1CustomAuthForgotPassword500
  status: 500
}

export type postV1CustomAuthForgotPasswordResponseSuccess = (postV1CustomAuthForgotPasswordResponse200) & {
  headers: Headers;
};
export type postV1CustomAuthForgotPasswordResponseError = (postV1CustomAuthForgotPasswordResponse500) & {
  headers: Headers;
};

export type postV1CustomAuthForgotPasswordResponse = (postV1CustomAuthForgotPasswordResponseSuccess | postV1CustomAuthForgotPasswordResponseError)

export const getPostV1CustomAuthForgotPasswordUrl = () => {




  return `/v1/custom/auth/forgot-password`
}

/**
 * Gera token de reset (uso único, 1h). Resposta sempre 200.
 */
export const postV1CustomAuthForgotPassword = async (postV1CustomAuthForgotPasswordBody?: PostV1CustomAuthForgotPasswordBody, options?: RequestInit): Promise<postV1CustomAuthForgotPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomAuthForgotPasswordBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAuthForgotPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomAuthForgotPasswordResponse
}


export type postV1CustomAuthResetPasswordResponse200 = {
  data: PostV1CustomAuthResetPassword200
  status: 200
}

export type postV1CustomAuthResetPasswordResponse400 = {
  data: PostV1CustomAuthResetPassword400
  status: 400
}

export type postV1CustomAuthResetPasswordResponse500 = {
  data: PostV1CustomAuthResetPassword500
  status: 500
}

export type postV1CustomAuthResetPasswordResponseSuccess = (postV1CustomAuthResetPasswordResponse200) & {
  headers: Headers;
};
export type postV1CustomAuthResetPasswordResponseError = (postV1CustomAuthResetPasswordResponse400 | postV1CustomAuthResetPasswordResponse500) & {
  headers: Headers;
};

export type postV1CustomAuthResetPasswordResponse = (postV1CustomAuthResetPasswordResponseSuccess | postV1CustomAuthResetPasswordResponseError)

export const getPostV1CustomAuthResetPasswordUrl = () => {




  return `/v1/custom/auth/reset-password`
}

/**
 * Troca a senha usando token de reset (uso único, 1h).
 */
export const postV1CustomAuthResetPassword = async (postV1CustomAuthResetPasswordBody?: PostV1CustomAuthResetPasswordBody, options?: RequestInit): Promise<postV1CustomAuthResetPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomAuthResetPasswordBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAuthResetPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomAuthResetPasswordResponse
}


export type postV1CustomCollectionsIdUseResponse200 = {
  data: PostV1CustomCollectionsIdUse200
  status: 200
}

export type postV1CustomCollectionsIdUseResponse401 = {
  data: PostV1CustomCollectionsIdUse401
  status: 401
}

export type postV1CustomCollectionsIdUseResponse404 = {
  data: PostV1CustomCollectionsIdUse404
  status: 404
}

export type postV1CustomCollectionsIdUseResponseSuccess = (postV1CustomCollectionsIdUseResponse200) & {
  headers: Headers;
};
export type postV1CustomCollectionsIdUseResponseError = (postV1CustomCollectionsIdUseResponse401 | postV1CustomCollectionsIdUseResponse404) & {
  headers: Headers;
};

export type postV1CustomCollectionsIdUseResponse = (postV1CustomCollectionsIdUseResponseSuccess | postV1CustomCollectionsIdUseResponseError)

export const getPostV1CustomCollectionsIdUseUrl = (id: string,) => {




  return `/v1/custom/collections/${id}/use`
}

/**
 * Registra uso de coletânea pública (1x por usuário×coletânea; credita +5 ao dono)
 */
export const postV1CustomCollectionsIdUse = async (id: string, options?: RequestInit): Promise<postV1CustomCollectionsIdUseResponse> => {

  const res = await fetch(getPostV1CustomCollectionsIdUseUrl(id),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomCollectionsIdUseResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomCollectionsIdUseResponse
}


export type getV1CustomRankingResponse200 = {
  data: GetV1CustomRanking200
  status: 200
}

export type getV1CustomRankingResponseSuccess = (getV1CustomRankingResponse200) & {
  headers: Headers;
};
;

export type getV1CustomRankingResponse = (getV1CustomRankingResponseSuccess)

export const getGetV1CustomRankingUrl = (params?: GetV1CustomRankingParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/custom/ranking?${stringifiedParams}` : `/v1/custom/ranking`
}

/**
 * Ranking global de contribuidores (janela week|all; desempate por ponto mais antigo)
 */
export const getV1CustomRanking = async (params?: GetV1CustomRankingParams, options?: RequestInit): Promise<getV1CustomRankingResponse> => {

  const res = await fetch(getGetV1CustomRankingUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomRankingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomRankingResponse
}


export type getV1CustomRankingMeResponse200 = {
  data: GetV1CustomRankingMe200
  status: 200
}

export type getV1CustomRankingMeResponse401 = {
  data: GetV1CustomRankingMe401
  status: 401
}

export type getV1CustomRankingMeResponseSuccess = (getV1CustomRankingMeResponse200) & {
  headers: Headers;
};
export type getV1CustomRankingMeResponseError = (getV1CustomRankingMeResponse401) & {
  headers: Headers;
};

export type getV1CustomRankingMeResponse = (getV1CustomRankingMeResponseSuccess | getV1CustomRankingMeResponseError)

export const getGetV1CustomRankingMeUrl = (params?: GetV1CustomRankingMeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/custom/ranking/me?${stringifiedParams}` : `/v1/custom/ranking/me`
}

/**
 * Posição do usuário autenticado no ranking (week|all)
 */
export const getV1CustomRankingMe = async (params?: GetV1CustomRankingMeParams, options?: RequestInit): Promise<getV1CustomRankingMeResponse> => {

  const res = await fetch(getGetV1CustomRankingMeUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomRankingMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomRankingMeResponse
}


export type getV1CustomWeeklyTasksResponse200 = {
  data: GetV1CustomWeeklyTasks200
  status: 200
}

export type getV1CustomWeeklyTasksResponse401 = {
  data: GetV1CustomWeeklyTasks401
  status: 401
}

export type getV1CustomWeeklyTasksResponseSuccess = (getV1CustomWeeklyTasksResponse200) & {
  headers: Headers;
};
export type getV1CustomWeeklyTasksResponseError = (getV1CustomWeeklyTasksResponse401) & {
  headers: Headers;
};

export type getV1CustomWeeklyTasksResponse = (getV1CustomWeeklyTasksResponseSuccess | getV1CustomWeeklyTasksResponseError)

export const getGetV1CustomWeeklyTasksUrl = () => {




  return `/v1/custom/weekly-tasks`
}

/**
 * Tarefas semanais do usuário autenticado (3 rotativas, reset domingo 00:00 UTC-3)
 */
export const getV1CustomWeeklyTasks = async ( options?: RequestInit): Promise<getV1CustomWeeklyTasksResponse> => {

  const res = await fetch(getGetV1CustomWeeklyTasksUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomWeeklyTasksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomWeeklyTasksResponse
}


export type postV1CustomWeeklyTasksTaskIdCompleteResponse200 = {
  data: PostV1CustomWeeklyTasksTaskIdComplete200
  status: 200
}

export type postV1CustomWeeklyTasksTaskIdCompleteResponse401 = {
  data: PostV1CustomWeeklyTasksTaskIdComplete401
  status: 401
}

export type postV1CustomWeeklyTasksTaskIdCompleteResponse404 = {
  data: PostV1CustomWeeklyTasksTaskIdComplete404
  status: 404
}

export type postV1CustomWeeklyTasksTaskIdCompleteResponseSuccess = (postV1CustomWeeklyTasksTaskIdCompleteResponse200) & {
  headers: Headers;
};
export type postV1CustomWeeklyTasksTaskIdCompleteResponseError = (postV1CustomWeeklyTasksTaskIdCompleteResponse401 | postV1CustomWeeklyTasksTaskIdCompleteResponse404) & {
  headers: Headers;
};

export type postV1CustomWeeklyTasksTaskIdCompleteResponse = (postV1CustomWeeklyTasksTaskIdCompleteResponseSuccess | postV1CustomWeeklyTasksTaskIdCompleteResponseError)

export const getPostV1CustomWeeklyTasksTaskIdCompleteUrl = (taskId: string,) => {




  return `/v1/custom/weekly-tasks/${taskId}/complete`
}

/**
 * Marca tarefa semanal como concluída (idempotente; +15 na 1a vez da semana)
 */
export const postV1CustomWeeklyTasksTaskIdComplete = async (taskId: string, options?: RequestInit): Promise<postV1CustomWeeklyTasksTaskIdCompleteResponse> => {

  const res = await fetch(getPostV1CustomWeeklyTasksTaskIdCompleteUrl(taskId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomWeeklyTasksTaskIdCompleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomWeeklyTasksTaskIdCompleteResponse
}


export type postV1CustomCollectionsIdReportResponse200 = {
  data: PostV1CustomCollectionsIdReport200
  status: 200
}

export type postV1CustomCollectionsIdReportResponse401 = {
  data: PostV1CustomCollectionsIdReport401
  status: 401
}

export type postV1CustomCollectionsIdReportResponse404 = {
  data: PostV1CustomCollectionsIdReport404
  status: 404
}

export type postV1CustomCollectionsIdReportResponseSuccess = (postV1CustomCollectionsIdReportResponse200) & {
  headers: Headers;
};
export type postV1CustomCollectionsIdReportResponseError = (postV1CustomCollectionsIdReportResponse401 | postV1CustomCollectionsIdReportResponse404) & {
  headers: Headers;
};

export type postV1CustomCollectionsIdReportResponse = (postV1CustomCollectionsIdReportResponseSuccess | postV1CustomCollectionsIdReportResponseError)

export const getPostV1CustomCollectionsIdReportUrl = (id: string,) => {




  return `/v1/custom/collections/${id}/report`
}

/**
 * Reporta coletânea (esconde do catálogo público até revisão da curadoria)
 */
export const postV1CustomCollectionsIdReport = async (id: string,
    postV1CustomCollectionsIdReportBody?: PostV1CustomCollectionsIdReportBody, options?: RequestInit): Promise<postV1CustomCollectionsIdReportResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomCollectionsIdReportUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomCollectionsIdReportBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomCollectionsIdReportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomCollectionsIdReportResponse
}


export type postV1CustomAdminPromoteMusicResponse200 = {
  data: PostV1CustomAdminPromoteMusic200
  status: 200
}

export type postV1CustomAdminPromoteMusicResponse400 = {
  data: PostV1CustomAdminPromoteMusic400
  status: 400
}

export type postV1CustomAdminPromoteMusicResponse401 = {
  data: PostV1CustomAdminPromoteMusic401
  status: 401
}

export type postV1CustomAdminPromoteMusicResponse403 = {
  data: PostV1CustomAdminPromoteMusic403
  status: 403
}

export type postV1CustomAdminPromoteMusicResponseSuccess = (postV1CustomAdminPromoteMusicResponse200) & {
  headers: Headers;
};
export type postV1CustomAdminPromoteMusicResponseError = (postV1CustomAdminPromoteMusicResponse400 | postV1CustomAdminPromoteMusicResponse401 | postV1CustomAdminPromoteMusicResponse403) & {
  headers: Headers;
};

export type postV1CustomAdminPromoteMusicResponse = (postV1CustomAdminPromoteMusicResponseSuccess | postV1CustomAdminPromoteMusicResponseError)

export const getPostV1CustomAdminPromoteMusicUrl = () => {




  return `/v1/custom/admin/promote-music`
}

/**
 * Promove faixa custom ao acervo oficial (curador; +50 pts, badge Autor Oficial, crédito permanente)
 */
export const postV1CustomAdminPromoteMusic = async (postV1CustomAdminPromoteMusicBody?: PostV1CustomAdminPromoteMusicBody, options?: RequestInit): Promise<postV1CustomAdminPromoteMusicResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostV1CustomAdminPromoteMusicUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1CustomAdminPromoteMusicBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomAdminPromoteMusicResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomAdminPromoteMusicResponse
}


export type getV1CustomNotificationsResponse200 = {
  data: GetV1CustomNotifications200
  status: 200
}

export type getV1CustomNotificationsResponse401 = {
  data: GetV1CustomNotifications401
  status: 401
}

export type getV1CustomNotificationsResponseSuccess = (getV1CustomNotificationsResponse200) & {
  headers: Headers;
};
export type getV1CustomNotificationsResponseError = (getV1CustomNotificationsResponse401) & {
  headers: Headers;
};

export type getV1CustomNotificationsResponse = (getV1CustomNotificationsResponseSuccess | getV1CustomNotificationsResponseError)

export const getGetV1CustomNotificationsUrl = () => {




  return `/v1/custom/notifications`
}

/**
 * Notificações não lidas do usuário autenticado
 */
export const getV1CustomNotifications = async ( options?: RequestInit): Promise<getV1CustomNotificationsResponse> => {

  const res = await fetch(getGetV1CustomNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomNotificationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomNotificationsResponse
}


export type postV1CustomNotificationsReadAllResponse200 = {
  data: PostV1CustomNotificationsReadAll200
  status: 200
}

export type postV1CustomNotificationsReadAllResponse401 = {
  data: PostV1CustomNotificationsReadAll401
  status: 401
}

export type postV1CustomNotificationsReadAllResponseSuccess = (postV1CustomNotificationsReadAllResponse200) & {
  headers: Headers;
};
export type postV1CustomNotificationsReadAllResponseError = (postV1CustomNotificationsReadAllResponse401) & {
  headers: Headers;
};

export type postV1CustomNotificationsReadAllResponse = (postV1CustomNotificationsReadAllResponseSuccess | postV1CustomNotificationsReadAllResponseError)

export const getPostV1CustomNotificationsReadAllUrl = () => {




  return `/v1/custom/notifications/read-all`
}

/**
 * Marca todas as notificações do usuário como lidas
 */
export const postV1CustomNotificationsReadAll = async ( options?: RequestInit): Promise<postV1CustomNotificationsReadAllResponse> => {

  const res = await fetch(getPostV1CustomNotificationsReadAllUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1CustomNotificationsReadAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1CustomNotificationsReadAllResponse
}


export type getV1CustomSeasonalEventResponse200 = {
  data: GetV1CustomSeasonalEvent200
  status: 200
}

export type getV1CustomSeasonalEventResponseSuccess = (getV1CustomSeasonalEventResponse200) & {
  headers: Headers;
};
;

export type getV1CustomSeasonalEventResponse = (getV1CustomSeasonalEventResponseSuccess)

export const getGetV1CustomSeasonalEventUrl = () => {




  return `/v1/custom/seasonal-event`
}

/**
 * Evento sazonal ativo (multiplicador de pontos) — público, para banner na Comunidade
 */
export const getV1CustomSeasonalEvent = async ( options?: RequestInit): Promise<getV1CustomSeasonalEventResponse> => {

  const res = await fetch(getGetV1CustomSeasonalEventUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CustomSeasonalEventResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CustomSeasonalEventResponse
}


