/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type {
  GetV1Albums200,
  GetV1Albums500,
  GetV1AlbumsId200,
  GetV1AlbumsId404,
  GetV1AlbumsId500,
  GetV1AlbumsIdParams,
  GetV1AlbumsParams
} from '../model';


export type getV1AlbumsResponse200 = {
  data: GetV1Albums200
  status: 200
}

export type getV1AlbumsResponse500 = {
  data: GetV1Albums500
  status: 500
}

export type getV1AlbumsResponseSuccess = (getV1AlbumsResponse200) & {
  headers: Headers;
};
export type getV1AlbumsResponseError = (getV1AlbumsResponse500) & {
  headers: Headers;
};

export type getV1AlbumsResponse = (getV1AlbumsResponseSuccess | getV1AlbumsResponseError)

export const getGetV1AlbumsUrl = (params: GetV1AlbumsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/albums?${stringifiedParams}` : `/v1/albums`
}

/**
 * Lista de coletâneas com paginação e filtro por idioma
 */
export const getV1Albums = async (params: GetV1AlbumsParams, options?: RequestInit): Promise<getV1AlbumsResponse> => {

  const res = await fetch(getGetV1AlbumsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1AlbumsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1AlbumsResponse
}


export type getV1AlbumsIdResponse200 = {
  data: GetV1AlbumsId200
  status: 200
}

export type getV1AlbumsIdResponse404 = {
  data: GetV1AlbumsId404
  status: 404
}

export type getV1AlbumsIdResponse500 = {
  data: GetV1AlbumsId500
  status: 500
}

export type getV1AlbumsIdResponseSuccess = (getV1AlbumsIdResponse200) & {
  headers: Headers;
};
export type getV1AlbumsIdResponseError = (getV1AlbumsIdResponse404 | getV1AlbumsIdResponse500) & {
  headers: Headers;
};

export type getV1AlbumsIdResponse = (getV1AlbumsIdResponseSuccess | getV1AlbumsIdResponseError)

export const getGetV1AlbumsIdUrl = (id: string,
    params: GetV1AlbumsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/albums/${id}?${stringifiedParams}` : `/v1/albums/${id}`
}

/**
 * Detalhe de coletânea com músicas aninhadas (paridade: album_{id})
 */
export const getV1AlbumsId = async (id: string,
    params: GetV1AlbumsIdParams, options?: RequestInit): Promise<getV1AlbumsIdResponse> => {

  const res = await fetch(getGetV1AlbumsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1AlbumsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1AlbumsIdResponse
}


