/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type {
  GetV1Categories200Item,
  GetV1Categories500,
  GetV1CategoriesId200,
  GetV1CategoriesId404,
  GetV1CategoriesId500,
  GetV1CategoriesIdParams,
  GetV1CategoriesParams
} from '../model';


export type getV1CategoriesResponse200 = {
  data: GetV1Categories200Item[]
  status: 200
}

export type getV1CategoriesResponse500 = {
  data: GetV1Categories500
  status: 500
}

export type getV1CategoriesResponseSuccess = (getV1CategoriesResponse200) & {
  headers: Headers;
};
export type getV1CategoriesResponseError = (getV1CategoriesResponse500) & {
  headers: Headers;
};

export type getV1CategoriesResponse = (getV1CategoriesResponseSuccess | getV1CategoriesResponseError)

export const getGetV1CategoriesUrl = (params: GetV1CategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/categories?${stringifiedParams}` : `/v1/categories`
}

/**
 * Lista categorias com coletâneas aninhadas (paridade: pt_categories)
 */
export const getV1Categories = async (params: GetV1CategoriesParams, options?: RequestInit): Promise<getV1CategoriesResponse> => {

  const res = await fetch(getGetV1CategoriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CategoriesResponse
}


export type getV1CategoriesIdResponse200 = {
  data: GetV1CategoriesId200
  status: 200
}

export type getV1CategoriesIdResponse404 = {
  data: GetV1CategoriesId404
  status: 404
}

export type getV1CategoriesIdResponse500 = {
  data: GetV1CategoriesId500
  status: 500
}

export type getV1CategoriesIdResponseSuccess = (getV1CategoriesIdResponse200) & {
  headers: Headers;
};
export type getV1CategoriesIdResponseError = (getV1CategoriesIdResponse404 | getV1CategoriesIdResponse500) & {
  headers: Headers;
};

export type getV1CategoriesIdResponse = (getV1CategoriesIdResponseSuccess | getV1CategoriesIdResponseError)

export const getGetV1CategoriesIdUrl = (id: string,
    params: GetV1CategoriesIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/categories/${id}?${stringifiedParams}` : `/v1/categories/${id}`
}

/**
 * Detalhe de uma categoria com coletâneas aninhadas
 */
export const getV1CategoriesId = async (id: string,
    params: GetV1CategoriesIdParams, options?: RequestInit): Promise<getV1CategoriesIdResponse> => {

  const res = await fetch(getGetV1CategoriesIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1CategoriesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1CategoriesIdResponse
}


