/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Piano Louvor JA API
 * API propria drop-in replacement para api.louvorja.com.br.
 *
 * Fornece catalogo de musicas, hinos, albuns, categorias e biblia.
 *
 * **Endpoints de compatibilidade** (`/json_db/*`, `/file/*`, `/db/*`) nao aparecem nesta documentacao pois usam path matching dinamico.
 * OpenAPI spec version: 1.4.1
 */
import type {
  GetV1Health200
} from '../model';


export type getV1HealthResponse200 = {
  data: GetV1Health200
  status: 200
}

export type getV1HealthResponseSuccess = (getV1HealthResponse200) & {
  headers: Headers;
};
;

export type getV1HealthResponse = (getV1HealthResponseSuccess)

export const getGetV1HealthUrl = () => {




  return `/v1/health`
}

export const getV1Health = async ( options?: RequestInit): Promise<getV1HealthResponse> => {

  const res = await fetch(getGetV1HealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1HealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1HealthResponse
}


